// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYkXCDwdnUuX2mUOEMnYoCdC_762QTHj8',
    appId: '1:990853009165:web:ffe9df1e05f2c87e0d6a44',
    messagingSenderId: '990853009165',
    projectId: 'kora-mhapp',
    authDomain: 'kora-mhapp.firebaseapp.com',
    storageBucket: 'kora-mhapp.appspot.com',
    measurementId: 'G-RCFM80GKFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkxNWC6Jg6H9sgbpZiF_W1unU-5iIopu0',
    appId: '1:990853009165:android:d63b131306ffa15d0d6a44',
    messagingSenderId: '990853009165',
    projectId: 'kora-mhapp',
    storageBucket: 'kora-mhapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQgLxQlCf2pasZCMgEreakhwjLBijkOzQ',
    appId: '1:990853009165:ios:e1a22988c3f3ecf40d6a44',
    messagingSenderId: '990853009165',
    projectId: 'kora-mhapp',
    storageBucket: 'kora-mhapp.appspot.com',
    iosBundleId: 'com.example.koraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQgLxQlCf2pasZCMgEreakhwjLBijkOzQ',
    appId: '1:990853009165:ios:df7e3c3353a191e20d6a44',
    messagingSenderId: '990853009165',
    projectId: 'kora-mhapp',
    storageBucket: 'kora-mhapp.appspot.com',
    iosBundleId: 'com.example.koraApp.RunnerTests',
  );
}
